"""
Django settings for salon_backend project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# load_dotenv(BASE_DIR / ".env")
load_dotenv()

# Hyper Pay Basics Steps
# HYPERPAY_BASE_URL = os.getenv("HYPERPAY_BASE_URL", "https://test.oppwa.com")
# HYPERPAY_ENTITY_ID = os.getenv("HYPERPAY_ENTITY_ID", "YOUR_ENTITY_ID")
# HYPERPAY_AUTHORIZATION = os.getenv("HYPERPAY_AUTHORIZATION", "YOUR_AUTH_KEY")
# WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET", "change_this_secret")


# HYPERPAY_ENTITY_ID = os.getenv("HYPERPAY_ENTITY_ID")
# HYPERPAY_ACCESS_CODE = os.getenv("HYPERPAY_ACCESS_CODE")
# HYPERPAY_BASE_URL = os.getenv("HYPERPAY_BASE_URL", "https://test.oppwa.com")


HYPERPAY_BASE_URL = os.getenv("HYPERPAY_BASE_URL")
HYPERPAY_ENTITY_ID = os.getenv("HYPERPAY_ENTITY_ID")
HYPERPAY_ACCESS_TOKEN = os.getenv("HYPERPAY_ACCESS_TOKEN")

# 🔹 إعداد كائن HYPERPAY حتى يتعرف عليه الكود
HYPERPAY = {
    "BASE_URL": HYPERPAY_BASE_URL,
    "ENTITY_ID": HYPERPAY_ENTITY_ID,
    "ACCESS_TOKEN": HYPERPAY_ACCESS_TOKEN,
    "CURRENCY": "SAR",
    "TEST_MODE": True,
}



LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "file": {
            "class": "logging.FileHandler",
            "filename": BASE_DIR / "hyperpay_webhook.log",
        },
    },
    "loggers": {
        "payments": {"handlers": ["console", "file"], "level": "INFO", "propagate": True},
    },
}

# Twillo basic 
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_WHATSAPP_NUMBER = os.getenv('TWILIO_WHATSAPP_NUMBER')




# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-n)pk!1p!z1m)ub=yi!4z$uz%8_)plk-#_r&twy-&v4ftd1_8i8'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['localhost', '127.0.0.1', '::1', 'testserver', '*']



# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme
    'unfold.contrib.filters',  # Optional: Advanced admin filters
    'unfold.contrib.forms',    # Optional: Enhanced forms
    'unfold.contrib.inlines',  # Optional: Better inline forms
    'unfold.contrib.import_export',  # Optional: Import/Export functionality
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'salon',
    'payments',
    "jazzmin",
]
# jazzmin customize
JAZZMIN_SETTINGS = {
    "site_title": "Salon Dashboard",
    "site_header": "Salon Management",
    "site_brand": "Salon Admin",
    "welcome_sign": "مرحبا بك في لوحة إدارة الصالون 💇‍♀️",
    "copyright": "© 2025",
    "show_sidebar": True,
    "search_model": ["payments.Payment"],
    "order_with_respect_to": ["payments"],
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "icons": {
        "payments.Payment": "fas fa-credit-card",
        "payments.PaymentLog": "fas fa-file-invoice",
    },
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'salon_backend.mime_type_fix.MimeTypeFixMiddleware',  # Fix MIME type issues
]

ROOT_URLCONF = 'salon_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'salon' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'salon_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        'OPTIONS': {
            'timeout': 30,
            'init_command': "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL; PRAGMA cache_size=10000; PRAGMA temp_store=MEMORY;",
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ar'

TIME_ZONE = 'Asia/Riyadh'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Additional static files directories
STATICFILES_DIRS = [
    BASE_DIR / 'salon' / 'static',
    BASE_DIR.parent / 'public',  # For background images and assets
]

# Static files finders
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# MIME types for static files
import mimetypes
mimetypes.add_type("text/css", ".css")
mimetypes.add_type("application/javascript", ".js")

# Static files storage
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# Ensure proper MIME types for static files
import os
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'salon_backend.settings')
import mimetypes
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("application/javascript", ".js", True)
mimetypes.add_type("image/png", ".png", True)
mimetypes.add_type("image/jpeg", ".jpg", True)
mimetypes.add_type("image/jpeg", ".jpeg", True)
mimetypes.add_type("image/gif", ".gif", True)
mimetypes.add_type("image/svg+xml", ".svg", True)
mimetypes.add_type("font/woff", ".woff", True)
mimetypes.add_type("font/woff2", ".woff2", True)
mimetypes.add_type("font/ttf", ".ttf", True)

# Media files
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration (Hostinger)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.hostinger.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_USER = 'info@takweensoft.com'
EMAIL_HOST_PASSWORD = 'Muaz$#@asd0173'
DEFAULT_FROM_EMAIL = 'info@takweensoft.com'

# Salon Configuration
SALON_WEBSITE_NAME = 'صالون الجمال'
ADMIN_EMAIL = 'info@takweensoft.com'


# Frontend URL for redirects
FRONTEND_URL = 'http://localhost:5173'

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
    "http://localhost:5174",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
]

CORS_ALLOW_CREDENTIALS = True

# Additional CORS settings for development
CORS_ALLOW_ALL_ORIGINS = True  # Only for development - remove in production
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'cache-control',
    'pragma',
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

CORS_PREFLIGHT_MAX_AGE = 86400

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
}

# Unfold Admin Theme Configuration - Simple White & Black
UNFOLD = {
    "SITE_TITLE": "إدارة صالون Glámmy",
    "SITE_HEADER": "إدارة صالون Glámmy",
    "SITE_URL": "/",
    "SITE_ICON": {
        "light": lambda request: "/media/logo-05.png",
        "dark": lambda request: "/media/logo-05.png",
    },
    "SITE_LOGO": {
        "light": lambda request: "/media/logo-05.png",
        "dark": lambda request: "/media/logo-05.png",
    },
    "SITE_SYMBOL": "⚙️",  # Simple gear symbol
    "SHOW_HISTORY": False,
    "SHOW_VIEW_ON_SITE": False,
    "LOGIN": {
        "image": lambda r: "dd.png",  # Background image for login page
        "redirect_after": lambda r: "/admin/",
    },
    "STYLES": [
        "/static/salon/css/notification_widget.css",
    ],
    "SCRIPTS": [
        "/static/salon/js/notification_widget.js",
    ],
    # Navigation configuration
    "NAVIGATION": {
        "SHOW_ALL_APPS": True,  # Show all apps expanded by default
        "SHOW_SEARCH": True,
        "SHOW_BREADCRUMBS": True,
    },
    "COLORS": {
        "primary": {
            "50": "#FFFFFF",   # Pure white
            "100": "#F8F9FA",  # Light gray
            "200": "#E9ECEF",  # Light gray
            "300": "#DEE2E6",  # Medium light gray
            "400": "#CED4DA",  # Medium gray
            "500": "#6C757D",  # Dark gray
            "600": "#495057",  # Darker gray
            "700": "#343A40",  # Very dark gray
            "800": "#212529",  # Almost black
            "900": "#000000",  # Pure black
            "950": "#000000",  # Pure black
        }
    },
    "EXTENSIONS": {
        "modeltranslation": {
            "flags": {
                "en": "🇺🇸",
                "ar": "🇸🇦",
            },
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "الرئيسية",
                "separator": True,
                "items": [
                    {
                        "title": "لوحة التحكم",
                        "icon": "dashboard",
                        "link": "/admin/",
                    },
                ],
            },
            {
                "title": "إدارة الصالون",
                "separator": True,
                "items": [
                    {
                        "title": "الخدمات",
                        "icon": "design_services",
                        "link": "/admin/salon/service/",
                    },
                    {
                        "title": "الفئات",
                        "icon": "category",
                        "link": "/admin/salon/category/",
                    },
                    {
                        "title": "فئات الخدمات",
                        "icon": "category",
                        "link": "/admin/salon/servicecategory/",
                    },
                    {
                        "title": "عناصر الخدمات",
                        "icon": "list",
                        "link": "/admin/salon/serviceitem/",
                    },
                    {
                        "title": "شهادات العملاء",
                        "icon": "star",
                        "link": "/admin/salon/testimonial/",
                    },
                    {
                        "title": "الموظفين",
                        "icon": "people",
                        "link": "/admin/salon/staff/",
                    },
                    {
                        "title": "العملاء",
                        "icon": "person",
                        "link": "/admin/salon/customer/",
                    },
                    {
                        "title": "الحجوزات",
                        "icon": "event_note",
                        "link": "/admin/salon/booking/",
                    },
                ],
            },
            {
                "title": "المحتوى",
                "separator": True,
                "items": [
                    {
                        "title": "الصور الرئيسية",
                        "icon": "image",
                        "link": "/admin/salon/heroimage/",
                    },
                    {
                        "title": "شهادات العملاء",
                        "icon": "star",
                        "link": "/admin/salon/testimonial/",
                    },
                    {
                        "title": "كوبونات الخصم",
                        "icon": "local_offer",
                        "link": "/admin/salon/coupon/",
                    },
                    {
                        "title": "العروض والترقيات",
                        "icon": "campaign",
                        "link": "/admin/salon/offer/",
                    },
                ],
            },
            {
                "title": "الإعدادات",
                "separator": True,
                "items": [
                    {
                        "title": "معلومات الاتصال",
                        "icon": "contact_phone",
                        "link": "/admin/salon/contactinfo/",
                    },
                    {
                        "title": "إعدادات عامة",
                        "icon": "settings",
                        "link": "/admin/salon/config/",
                    },
                    {
                        "title": "أوقات العمل",
                        "icon": "schedule",
                        "link": "/admin/salon/workinghours/",
                    },
                    {
                        "title": "أيام الإجازة",
                        "icon": "event_busy",
                        "link": "/admin/salon/dayoff/",
                    },
                ],
            },
            {
                "title": "الإشعارات",
                "separator": True,
                "items": [
                    {
                        "title": "الإشعارات",
                        "icon": "notifications",
                        "link": "/admin/salon/notification/",
                    },
                    {
                        "title": "إعدادات الإشعارات",
                        "icon": "notifications_active",
                        "link": "/admin/salon/notificationsettings/",
                    },
                ],
            },
            {
                "title": "المدونة",
                "separator": True,
                "items": [
                    {
                        "title": "فئات المدونة",
                        "icon": "category",
                        "link": "/admin/salon/blogcategory/",
                    },
                    {
                        "title": "كتاب المدونة",
                        "icon": "person",
                        "link": "/admin/salon/blogauthor/",
                    },
                    {
                        "title": "مقالات المدونة",
                        "icon": "article",
                        "link": "/admin/salon/blogpost/",
                    },
                    {
                        "title": "مشتركو النشرة الإخبارية",
                        "icon": "subscriptions",
                        "link": "/admin/salon/newslettersubscriber/",
                    },
                ],
            },
            {
                "title": "المستخدمين والأذونات",
                "separator": True,
                "items": [
                    {
                        "title": "المستخدمين",
                        "icon": "person",
                        "link": "/admin/auth/user/",
                    },
                    {
                        "title": "المجموعات",
                        "icon": "group",
                        "link": "/admin/auth/group/",
                    },
                ],
            },
        ],
    },
}





STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
